APP_MODULES		        :=      ARMovieNative
APP_OPTIM		        :=      release
#APP_OPTIM		        :=      debug
#APP_ABI			    :=      all
APP_ABI			        :=      armeabi-v7a x86 arm64-v8a x86_64
#APP_ABI			    :=      armeabi-v7a x86 arm64-v8a x86_64
APP_PLATFORM            :=      android-15
APP_STL 		        :=      c++_shared
APP_CPPFLAGS 	        :=      -frtti -fexceptions
NDK_TOOLCHAIN_VERSION   :=      clang
